import { Template } from '../types/template';

export const TEMPLATES: Template[] = [
  {
    id: 'corp-blue',
    name: 'Corporate Blue',
    description: 'Classic corporate letterhead with blue accents',
    category: 'corporate',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'Your Company Name',
      tagline: 'Excellence in Business',
      logoType: 'preset',
      logoPreset: 'hexagon',
      addressLine1: '123 Business Avenue',
      addressLine2: 'Suite 100, City',
      phone: '+1 (555) 123-4567',
      email: 'contact@company.com',
      website: 'company.com',
    },
    style: {
      theme: 'classic-top',
      fontPair: 'executive',
      primaryColor: '#1e3a8a',
      secondaryColor: '#eab308',
      textColor: '#1e293b',
      paperBackground: 'solid-white',
      watermarkText: 'CONFIDENTIAL',
      showWatermark: false,
      accentBarPosition: 'top',
    },
    tags: ['corporate', 'classic', 'blue'],
    popular: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'modern-dark',
    name: 'Modern Dark',
    description: 'Sleek modern design with dark accents',
    category: 'modern',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'Your Company Name',
      tagline: 'Innovation Forward',
      logoType: 'initials',
      logoInitials: 'YC',
      addressLine1: '456 Tech Park',
      addressLine2: 'Floor 12, Silicon Valley',
      phone: '+1 (555) 987-6543',
      email: 'hello@company.com',
      website: 'company.tech',
    },
    style: {
      theme: 'modern-split',
      fontPair: 'modern',
      primaryColor: '#0f172a',
      secondaryColor: '#4f46e5',
      textColor: '#1e293b',
      paperBackground: 'solid-white',
      watermarkText: 'DRAFT',
      showWatermark: false,
      accentBarPosition: 'top',
    },
    tags: ['modern', 'dark', 'sleek'],
    popular: true,
    createdAt: '2026-01-15',
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    description: 'Clean, minimalist design for modern brands',
    category: 'minimal',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'Minimal Brand',
      tagline: 'Less is More',
      logoType: 'initials',
      logoInitials: 'MB',
      addressLine1: '789 Design Street',
      addressLine2: 'Creative District',
      phone: '+1 (555) 234-5678',
      email: 'studio@minimal.com',
      website: 'minimal.design',
    },
    style: {
      theme: 'minimalist-clean',
      fontPair: 'minimalist',
      primaryColor: '#111827',
      secondaryColor: '#e2e8f0',
      textColor: '#1e293b',
      paperBackground: 'solid-white',
      watermarkText: '',
      showWatermark: false,
      accentBarPosition: 'none',
    },
    tags: ['minimal', 'clean', 'modern'],
    popular: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'creative-studio',
    name: 'Creative Studio',
    description: 'Bold creative layout for agencies',
    category: 'creative',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'Creative Studio',
      tagline: 'Design that Inspires',
      logoType: 'preset',
      logoPreset: 'triad',
      addressLine1: '321 Art Lane',
      addressLine2: 'Downtown Creative Hub',
      phone: '+1 (555) 345-6789',
      email: 'info@creativestudio.com',
      website: 'creativestudio.com',
    },
    style: {
      theme: 'creative-block',
      fontPair: 'creative',
      primaryColor: '#701a20',
      secondaryColor: '#b58a3a',
      textColor: '#1e293b',
      paperBackground: 'warm-ivory',
      watermarkText: 'PORTFOLIO',
      showWatermark: true,
      accentBarPosition: 'left',
    },
    tags: ['creative', 'bold', 'agency'],
    popular: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'legal-premium',
    name: 'Legal Premium',
    description: 'Formal layout for law firms and legal documents',
    category: 'legal',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'Law Associates',
      tagline: 'Justice & Integrity',
      logoType: 'preset',
      logoPreset: 'crown',
      addressLine1: '555 Justice Blvd',
      addressLine2: 'Suite 2000',
      phone: '+1 (555) 456-7890',
      email: 'counsel@lawassociates.com',
      website: 'lawassociates.com',
    },
    style: {
      theme: 'classic-top',
      fontPair: 'executive',
      primaryColor: '#14532d',
      secondaryColor: '#d97706',
      textColor: '#1e293b',
      paperBackground: 'cream-texture',
      watermarkText: 'PRIVILEGED',
      showWatermark: true,
      accentBarPosition: 'top',
    },
    tags: ['legal', 'formal', 'premium'],
    popular: false,
    createdAt: '2026-03-01',
  },
  {
    id: 'healthcare',
    name: 'Healthcare Plus',
    description: 'Clean medical-themed stationery',
    category: 'healthcare',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'City Medical Center',
      tagline: 'Caring for Life',
      logoType: 'preset',
      logoPreset: 'hexagon',
      addressLine1: '742 Health Drive',
      addressLine2: 'Medical District',
      phone: '+1 (555) 567-8901',
      email: 'info@citymed.com',
      website: 'citymed.com',
    },
    style: {
      theme: 'modern-split',
      fontPair: 'modern',
      primaryColor: '#0d9488',
      secondaryColor: '#64748b',
      textColor: '#1e293b',
      paperBackground: 'solid-white',
      watermarkText: 'MEDICAL',
      showWatermark: false,
      accentBarPosition: 'top',
    },
    tags: ['healthcare', 'medical', 'clean'],
    popular: false,
    createdAt: '2026-03-10',
  },
  {
    id: 'education',
    name: 'Academic Excellence',
    description: 'Professional letterhead for educational institutions',
    category: 'education',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'University of Excellence',
      tagline: 'Empowering Minds Since 1950',
      logoType: 'preset',
      logoPreset: 'crown',
      addressLine1: '1 University Avenue',
      addressLine2: 'Academic District',
      phone: '+1 (555) 678-9012',
      email: 'info@university.edu',
      website: 'university.edu',
    },
    style: {
      theme: 'classic-top',
      fontPair: 'executive',
      primaryColor: '#701a20',
      secondaryColor: '#b58a3a',
      textColor: '#1e293b',
      paperBackground: 'cream-texture',
      watermarkText: 'EDUCATION',
      showWatermark: false,
      accentBarPosition: 'top',
    },
    tags: ['education', 'academic', 'classic'],
    popular: false,
    createdAt: '2026-03-15',
  },
  {
    id: 'construction',
    name: 'Builder Pro',
    description: 'Bold rugged design for construction firms',
    category: 'construction',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'BuildRight Construction',
      tagline: 'Building Tomorrow Today',
      logoType: 'preset',
      logoPreset: 'grid',
      addressLine1: '200 Industrial Way',
      addressLine2: 'Construction Zone',
      phone: '+1 (555) 789-0123',
      email: 'info@buildright.com',
      website: 'buildright.com',
    },
    style: {
      theme: 'side-ribbon',
      fontPair: 'modern',
      primaryColor: '#14532d',
      secondaryColor: '#d97706',
      textColor: '#1e293b',
      paperBackground: 'solid-white',
      watermarkText: 'SPECIFICATION',
      showWatermark: true,
      accentBarPosition: 'left',
    },
    tags: ['construction', 'industrial', 'bold'],
    popular: false,
    createdAt: '2026-04-01',
  },
  {
    id: 'restaurant',
    name: 'Culinary Arts',
    description: 'Elegant design for restaurants and hospitality',
    category: 'restaurant',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'La Maison Restaurant',
      tagline: 'Fine Dining Experience',
      logoType: 'preset',
      logoPreset: 'crown',
      addressLine1: '88 Gourmet Street',
      addressLine2: 'Downtown',
      phone: '+1 (555) 890-1234',
      email: 'reservations@lamaison.com',
      website: 'lamaison.com',
    },
    style: {
      theme: 'minimalist-clean',
      fontPair: 'creative',
      primaryColor: '#701a20',
      secondaryColor: '#b58a3a',
      textColor: '#1e293b',
      paperBackground: 'cream-texture',
      watermarkText: 'MENU',
      showWatermark: false,
      accentBarPosition: 'bottom',
    },
    tags: ['restaurant', 'hospitality', 'elegant'],
    popular: false,
    createdAt: '2026-04-10',
  },
  {
    id: 'real-estate',
    name: 'Property Elite',
    description: 'Premium design for real estate agencies',
    category: 'real-estate',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'Elite Properties',
      tagline: 'Your Dream Home Awaits',
      logoType: 'preset',
      logoPreset: 'hexagon',
      addressLine1: '500 Luxury Row',
      addressLine2: 'Prime Location',
      phone: '+1 (555) 901-2345',
      email: 'info@eliteproperties.com',
      website: 'eliteproperties.com',
    },
    style: {
      theme: 'modern-split',
      fontPair: 'executive',
      primaryColor: '#1e3a8a',
      secondaryColor: '#eab308',
      textColor: '#1e293b',
      paperBackground: 'warm-ivory',
      watermarkText: 'PREMIUM',
      showWatermark: true,
      accentBarPosition: 'top',
    },
    tags: ['real-estate', 'premium', 'luxury'],
    popular: false,
    createdAt: '2026-04-15',
  },
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    description: 'Modern tech-forward design for startups',
    category: 'technology',
    documentType: 'letter',
    thumbnail: '',
    company: {
      name: 'NexGen Technologies',
      tagline: 'Building the Future',
      logoType: 'preset',
      logoPreset: 'infinity',
      addressLine1: '100 Innovation Drive',
      addressLine2: 'Tech Park',
      phone: '+1 (555) 012-3456',
      email: 'hello@nexgen.dev',
      website: 'nexgen.dev',
    },
    style: {
      theme: 'side-ribbon',
      fontPair: 'modern',
      primaryColor: '#0f172a',
      secondaryColor: '#4f46e5',
      textColor: '#1e293b',
      paperBackground: 'solid-white',
      watermarkText: 'TECH',
      showWatermark: false,
      accentBarPosition: 'left',
    },
    tags: ['technology', 'startup', 'modern'],
    popular: true,
    createdAt: '2026-05-01',
  },
  {
    id: 'corp-proposal',
    name: 'Corporate Proposal',
    description: 'Professional proposal template for enterprise',
    category: 'corporate',
    documentType: 'proposal',
    thumbnail: '',
    company: {
      name: 'Enterprise Solutions Inc.',
      tagline: 'Driving Business Growth',
      logoType: 'preset',
      logoPreset: 'hexagon',
      addressLine1: '200 Corporate Blvd',
      addressLine2: 'Suite 500',
      phone: '+1 (555) 111-2222',
      email: 'info@enterprise.com',
      website: 'enterprise.com',
    },
    style: {
      theme: 'classic-top',
      fontPair: 'executive',
      primaryColor: '#0f172a',
      secondaryColor: '#4f46e5',
      textColor: '#1e293b',
      paperBackground: 'solid-white',
      watermarkText: 'PROPOSAL',
      showWatermark: true,
      accentBarPosition: 'top',
    },
    tags: ['corporate', 'proposal', 'enterprise'],
    popular: false,
    createdAt: '2026-05-10',
  },
  {
    id: 'invoice-modern',
    name: 'Modern Invoice',
    description: 'Clean invoice template for modern businesses',
    category: 'modern',
    documentType: 'invoice',
    thumbnail: '',
    company: {
      name: 'Your Business',
      tagline: 'Professional Services',
      logoType: 'initials',
      logoInitials: 'YB',
      addressLine1: '123 Commerce St',
      addressLine2: 'Business District',
      phone: '+1 (555) 333-4444',
      email: 'billing@yourbusiness.com',
      website: 'yourbusiness.com',
    },
    style: {
      theme: 'modern-split',
      fontPair: 'modern',
      primaryColor: '#0f172a',
      secondaryColor: '#4f46e5',
      textColor: '#1e293b',
      paperBackground: 'solid-white',
      watermarkText: 'INVOICE',
      showWatermark: false,
      accentBarPosition: 'top',
    },
    tags: ['invoice', 'billing', 'modern'],
    popular: false,
    createdAt: '2026-05-15',
  },
];
